# Site settings
title: RDcastle Blog
name: RDcastle Blog # your name
email: rsdst5124@gmail.com # your email address
description: >
    A man leaving for Mordor. # this means to ignore newlines until "baseurl:"
baseurl:  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: # your Twitter username
github_username: rdcastle # your Github username
disqus_username: # your disqus username

google-analytics: # add it if you have one

skillstree: false # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
